=== wolfgangreder/mti/trunk/mti/datamodel/src/at/motriv/datamodel/entities/contact/contacts.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/contacts.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE contacts SYSTEM "contacts.dtd">

    <contacts>
    ...
    </contacts>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT contacts (contact)*>
<!ATTLIST contacts
    version CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT contact (name,type,(type*),(memo?|www?|email?|country?|city?|zip?|address2?|address1?|phone1?|phone2?|fax?|shopaddress?))>
<!ATTLIST contact
    id CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>

<!ELEMENT type (EMPTY)>
<!ATTLIST type
   name CDATA #REQUIRED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT address1 (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT address2 (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT zip (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT city (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT country (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT email (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT www (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT shopaddress (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT memo (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT phone1 (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT phone2 (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT fax (#PCDATA)>

=== wolfgangreder/mti/branches/old/mti/datamodel/src/at/motriv/datamodel/entities/contact/impl/defaultcontacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contacts PUBLIC "-//at.motriv//contacts//EN" "http://www.motriv.at/dtd/contacts.dtd">
<contacts version="1.0">
  <contact id="2987855c-2d02-4ff6-8697-1779ba5edd7a">
    <name>unbekannt</name>
    <type name="MANUFACTURER"/>
    <type name="RETAILER"/>
  </contact>
  <contact id="ca6c1920-1aed-46a4-91dd-59b98bc34821">
    <name>Eigenbau</name>
    <type name="MANUFACTURER"/>
  </contact>
  <contact id="aa0081c2-413d-447a-abc3-3e58897174b2">
    <name>keiner</name>
    <type name="RETAILER"/>
  </contact>
</contacts>
