=== wolfgangreder/mti/branches/old/mti/datamodel/src/at/motriv/datamodel/entities/scale/scales.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/scales.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE scales SYSTEM "scales.dtd">

    <scales>
    ...
    </scales>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT scales (scale)*>
<!ATTLIST scales
    version CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT scale (name)*>
<!ATTLIST scale
    family CDATA #REQUIRED
    trackwidth CDATA #REQUIRED
    scale CDATA #REQUIRED
    id CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
    xml:lang CDATA #IMPLIED
  >

=== wolfgangreder/mti/trunk/mti/datamodel/src/at/motriv/datamodel/entities/scale/impl/scales.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scales PUBLIC "-//at.motriv//scales//EN" "http://www.motriv.at/dtd/scales.dtd">
<scales version="1.0">
  <!--
    Nennspurweiten nach NEM010
    http://www.morop.org/de/normes/nem010_d.pdf
  -->
  <scale id="8fd04308-f6e3-4f7e-94fd-e10a4d1b85d6" scale="5.5" trackwidth="260" family="8fd04308-f6e3-4f7e-94fd-e10a4d1b85d6">
    <name>X</name>
  </scale>
  <scale id="0a59283a-27cb-4a9d-8e04-132f0cec69c8" scale="5.5" trackwidth="184" family="8fd04308-f6e3-4f7e-94fd-e10a4d1b85d6">
    <name>Xm</name>
  </scale>
  <scale id="616d45de-44ca-4e6d-8a68-9952ba361611" scale="5.5" trackwidth="127" family="8fd04308-f6e3-4f7e-94fd-e10a4d1b85d6">
    <name>Xe</name>
  </scale>
  <scale id="7ec8e936-30c3-4611-980c-7a8cfce67633" scale="5.5" trackwidth="89" family="8fd04308-f6e3-4f7e-94fd-e10a4d1b85d6">
    <name xml:lang="de">Xf</name>
    <name>Xi</name>
  </scale>

  <scale id="cd251866-0edb-410a-a4d0-aa19ec29542f" scale="8" trackwidth="184" family="cd251866-0edb-410a-a4d0-aa19ec29542f">
    <name>VII</name>
  </scale>
  <scale id="7b14cffa-b5e7-4a59-8b12-e8a98974dcb3" scale="8" trackwidth="127" family="cd251866-0edb-410a-a4d0-aa19ec29542f">
    <name>VIIm</name>
  </scale>
  <scale id="c83f1431-d264-4a0c-8d81-53247ec4d6d0" scale="8" trackwidth="89" family="cd251866-0edb-410a-a4d0-aa19ec29542f">
    <name>VIIe</name>
  </scale>
  <scale id="c0354f66-8423-4728-9c73-bd82c286530d" scale="8" trackwidth="64" family="cd251866-0edb-410a-a4d0-aa19ec29542f">
    <name xml:lang="de">VIIf</name>
    <name>VIIi</name>
  </scale>
  
  <scale id="25c144cf-a1b7-4d84-b2af-b02550d94764" scale="11" trackwidth="127" family="25c144cf-a1b7-4d84-b2af-b02550d94764">
    <name>V</name>
  </scale> 
  <scale id="81f80b43-5058-4505-94dd-7962a945b605" scale="11" trackwidth="89" family="25c144cf-a1b7-4d84-b2af-b02550d94764">
    <name>Vm</name>
  </scale>
  <scale id="2f1fd591-2cc6-4fd2-89af-75e647b64d09" scale="11" trackwidth="64" family="25c144cf-a1b7-4d84-b2af-b02550d94764">
    <name>Ve</name>
  </scale>
  <scale id="4b186536-8c92-497a-9c10-1e810ccc89fb" scale="11" trackwidth="45" family="25c144cf-a1b7-4d84-b2af-b02550d94764">
    <name xml:lang="de">Vf</name>
    <name>Vi</name>
  </scale>
  
  <scale id="e762ab9e-fe04-43cb-95cd-58be1cc4e406" scale="16" trackwidth="89" family="e762ab9e-fe04-43cb-95cd-58be1cc4e406">
    <name>III</name>
  </scale>
  <scale id="8b1ab941-3409-4b59-9ae1-dac76f9f4931" scale="16" trackwidth="64" family="e762ab9e-fe04-43cb-95cd-58be1cc4e406">
    <name>IIIm</name>
  </scale>
  <scale id="4b0bd985-e1ac-4d3c-bbcc-bbdca5b07d93" scale="16" trackwidth="45" family="e762ab9e-fe04-43cb-95cd-58be1cc4e406">
    <name>IIIe</name>
  </scale>
  <scale id="d6aa7a4a-0135-48df-8ab6-b20bd9cd25be" scale="16" trackwidth="32" family="e762ab9e-fe04-43cb-95cd-58be1cc4e406">
    <name xml:lang="de">IIIf</name>
    <name>IIIi</name>
  </scale>
  
  <scale id="83987eb6-9161-47d7-8aca-df949af2cfda" scale="22.5" trackwidth="64" family="83987eb6-9161-47d7-8aca-df949af2cfda">
    <name>II</name>
  </scale>
  <scale id="5d8a9713-b8a6-4a5f-93b3-d2b53b8f42d9" scale="22.5" trackwidth="45" family="83987eb6-9161-47d7-8aca-df949af2cfda">
    <name>IIm</name>
  </scale>
  <scale id="83c5aada-7b28-455d-a749-fb1fa746ffa6" scale="22.5" trackwidth="32" family="83987eb6-9161-47d7-8aca-df949af2cfda">
    <name>IIe</name>
  </scale>
  <scale id="a183994d-8696-4fee-a27b-1a4a13e9a753" scale="22.5" trackwidth="22.5" family="83987eb6-9161-47d7-8aca-df949af2cfda">
    <name xml:lang="de">IIf</name>
    <name>IIi</name>
  </scale>
  
  <scale id="76965643-4819-420a-a450-466c3b7b21be" scale="32" trackwidth="45" family="76965643-4819-420a-a450-466c3b7b21be">
    <name>I</name>
  </scale>
  <scale id="20895b62-3e0c-4cfa-b902-bad0c6b2d293" scale="32" trackwidth="32" family="76965643-4819-420a-a450-466c3b7b21be">
    <name>Im</name>
  </scale>
  <scale id="111d5474-18ca-4062-8ffd-182c1dcf23b0" scale="32" trackwidth="22.5" family="76965643-4819-420a-a450-466c3b7b21be">
    <name>Ie</name>
  </scale>
  <scale id="f9575525-2737-42a8-a202-4723880ee2bd" scale="32" trackwidth="16.5" family="76965643-4819-420a-a450-466c3b7b21be">
    <name xml:lang="de">If</name>
    <name>Ii</name>
  </scale>
  
  <scale id="7052e84a-4782-4bd6-acd9-189e25b8cc70" scale="45" trackwidth="32" family="7052e84a-4782-4bd6-acd9-189e25b8cc70">
    <name>0</name>
  </scale>
  <scale id="8c9b751f-d08b-4289-9981-f66201de842e" scale="45" trackwidth="22.5" family="7052e84a-4782-4bd6-acd9-189e25b8cc70">
    <name>0m</name>
  </scale>
  <scale id="90826d8a-54d5-49db-aeeb-a17f1a5c59dd" scale="45" trackwidth="16.5" family="7052e84a-4782-4bd6-acd9-189e25b8cc70">
    <name>0e</name>
  </scale>
  <scale id="5c6fb56a-6042-4b1a-b57b-02d0454da279" scale="45" trackwidth="12" family="7052e84a-4782-4bd6-acd9-189e25b8cc70">
    <name xml:lang="de">Of</name>
    <name>0i</name>
  </scale>
  
  <scale id="47155285-c493-40e9-954c-d0080e63bae4" scale="43.5" trackwidth="32" family="47155285-c493-40e9-954c-d0080e63bae4">
    <name>7 mm scale</name>
  </scale>
  <scale id="7406b4a5-6f19-40d9-8623-40e5069ab127" scale="43.5" trackwidth="22.5" family="47155285-c493-40e9-954c-d0080e63bae4">
    <name>0m</name>
  </scale>
  <scale id="a0f2a94c-e6db-48d1-9dec-c4cd7aafae81" scale="43.5" trackwidth="16.5" family="47155285-c493-40e9-954c-d0080e63bae4">
    <name>0e</name>
  </scale>
  <scale id="fdc13c57-bf6a-4829-a890-0959ec7ba04b" scale="43.5" trackwidth="12" family="47155285-c493-40e9-954c-d0080e63bae4">
    <name>0i</name>
  </scale>
  
  <scale id="5218e56c-c261-4cb4-b1ec-857ad18adc59" scale="64" trackwidth="22.5" family="5218e56c-c261-4cb4-b1ec-857ad18adc59">
    <name>S</name>
  </scale>
  <scale id="0e6addfb-69bc-44e0-917a-598f54d63aad" scale="64" trackwidth="16.5" family="5218e56c-c261-4cb4-b1ec-857ad18adc59">
    <name>Sm</name>
  </scale>
  <scale id="ea19cc4f-19d3-4a27-8c9d-0c2ad73d151a" scale="64" trackwidth="12" family="5218e56c-c261-4cb4-b1ec-857ad18adc59">
    <name>Se</name>
  </scale>
  <scale id="0a5b26cd-8c3e-442c-91f1-82c7b6c71d40" scale="64" trackwidth="9" family="5218e56c-c261-4cb4-b1ec-857ad18adc59">
    <name xml:lang="de">Sf</name>
    <name>Si</name>
  </scale>
  
  <scale id="d5fee291-ce11-4b15-acd4-c20c6075d3f1" scale="87" trackwidth="16.5" family="d5fee291-ce11-4b15-acd4-c20c6075d3f1">
    <name>H0</name>
    <name xml:lang="en">3.5 mm scale</name>
  </scale>
  <scale id="343184d2-b0e7-4e1b-8935-1904a9b80e27" scale="87" trackwidth="12" family="d5fee291-ce11-4b15-acd4-c20c6075d3f1">
    <name>H0m</name>
  </scale>
  <scale id="555ca43e-35c7-49c6-b2be-5874223f0cc8" scale="87" trackwidth="9" family="d5fee291-ce11-4b15-acd4-c20c6075d3f1">
    <name>H0e</name>
  </scale>
  <scale id="eb330213-d094-4344-a9b5-30af4bb0bcd4" scale="87" trackwidth="6.5" family="d5fee291-ce11-4b15-acd4-c20c6075d3f1">
    <name xml:lang="de">H0f</name>
    <name>H0i</name>
  </scale>

  <scale id="0b16f3ab-f519-41ee-886e-d95b3b69f935" scale="120" trackwidth="12" family="0b16f3ab-f519-41ee-886e-d95b3b69f935">
    <name>TT</name>
  </scale>
  <scale id="4bcf1351-2655-46fe-8d4e-0feae6ea9ba5" scale="120" trackwidth="9" family="0b16f3ab-f519-41ee-886e-d95b3b69f935">
    <name>TTm</name>
  </scale>
  <scale id="b216ae06-5327-481e-a65a-09aee7178750" scale="120" trackwidth="6.5" family="0b16f3ab-f519-41ee-886e-d95b3b69f935">
    <name>TTe</name>
  </scale>
  <scale id="20366b8d-5678-420d-9a1e-6a1cffb1a02a" scale="120" trackwidth="4.5" family="0b16f3ab-f519-41ee-886e-d95b3b69f935">
    <name xml:lang="de">TTf</name>
    <name>TTi</name>
  </scale>

  <scale id="66aa58ec-27e6-405a-ae68-402c36e4c7dd" scale="160" trackwidth="9" family="66aa58ec-27e6-405a-ae68-402c36e4c7dd">
    <name>N</name>
  </scale>
  <scale id="2c265fa6-6818-4bca-ae77-c62c2a1acef7" scale="160" trackwidth="6.5" family="66aa58ec-27e6-405a-ae68-402c36e4c7dd">
    <name>Nm</name>
  </scale>
  <scale id="8896d9d1-6cec-449e-8e23-4276794bd39e" scale="160" trackwidth="4.5" family="66aa58ec-27e6-405a-ae68-402c36e4c7dd">
    <name>Ne</name>
  </scale>

  <scale id="d0c4806c-a2be-4dab-a0df-f329a0873163" scale="220" trackwidth="6.5" family="d0c4806c-a2be-4dab-a0df-f329a0873163">
    <name>Z</name>
  </scale>
  <scale id="3244f01e-4119-4a1f-b892-99608b442bbb" scale="220" trackwidth="4.5" family="d0c4806c-a2be-4dab-a0df-f329a0873163">
    <name>Zm</name>
  </scale>
</scales>
